version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: notification_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - notification_network

volumes:
  rabbitmq_data:

networks:
  notification_network:
    driver: bridge