apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: go-rabbitmq-prod
resources:
  - ../../base
patches:
  - path: patch-configmap.yaml
  - path: patch-ingress.yaml
  - path: patch-rabbitmq.yaml