name: Build and Push Docker Images (DEV)

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build and Push Docker Images (DEV)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ api, worker ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push ${{ matrix.service }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: deployments/docker/Dockerfile.${{ matrix.service }}
          push: true
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/go-rabbitmq-notification-${{ matrix.service }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/go-rabbitmq-notification-${{ matrix.service }}:buildcache,mode=max
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/go-rabbitmq-notification-${{ matrix.service }}:dev
