name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push API
        uses: docker/build-push-action@v5
        with:
          context: .
          file: deployments/docker/Dockerfile.api
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/go-rabbitmq-notification-api:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/go-rabbitmq-notification-api:${{ github.sha }}

  build-worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Worker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: deployments/docker/Dockerfile.worker
          push: true
          tags: |
            docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/go-rabbitmq-notification-worker:latest
            docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/go-rabbitmq-notification-worker:${{ github.sha }}