name: Build and Push Docker Images

on:
  push:
    branches:
      - main
      - develop
    tags: [ 'v*' ]

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set Docker Tags
        id: vars
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "TAGS=${{ secrets.DOCKER_HUB_USERNAME }}/go-rabbitmq-notification-api:latest,${{ secrets.DOCKER_HUB_USERNAME }}/go-rabbitmq-notification-api:${GITHUB_SHA},${{ secrets.DOCKER_HUB_USERNAME }}/go-rabbitmq-notification-api:prod" >> $GITHUB_ENV
          else
            echo "TAGS=${{ secrets.DOCKER_HUB_USERNAME }}/go-rabbitmq-notification-api:dev-latest,${{ secrets.DOCKER_HUB_USERNAME }}/go-rabbitmq-notification-api:${GITHUB_SHA}-dev,${{ secrets.DOCKER_HUB_USERNAME }}/go-rabbitmq-notification-api:dev" >> $GITHUB_ENV
          fi

      - name: Build and push API
        uses: docker/build-push-action@v5
        with:
          context: .
          file: deployments/docker/Dockerfile.api
          push: true
          tags: ${{ env.TAGS }}

  build-worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set Docker Tags
        id: vars
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "TAGS=docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/go-rabbitmq-notification-worker:latest,docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/go-rabbitmq-notification-worker:${GITHUB_SHA},docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/go-rabbitmq-notification-worker:prod" >> $GITHUB_ENV
          else
            echo "TAGS=docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/go-rabbitmq-notification-worker:dev-latest,docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/go-rabbitmq-notification-worker:${GITHUB_SHA}-dev,docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/go-rabbitmq-notification-worker:dev" >> $GITHUB_ENV
          fi

      - name: Build and push Worker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: deployments/docker/Dockerfile.worker
          push: true
          tags: ${{ env.TAGS }}
