name: Build and Push Docker Images

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ api, worker ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set Docker Tags
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "TAG=prod" >> $GITHUB_ENV
          else
            echo "TAG=dev" >> $GITHUB_ENV
          fi

      - name: Build and push ${{ matrix.service }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: deployments/docker/Dockerfile.${{ matrix.service }}
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/go-rabbitmq-notification-${{ matrix.service }}:${{ env.TAG }}